<?xml version="1.0"?>

<robot name="kinect" xmlns:xacro="http://ros.org/wiki/xacro">

   <!-- Define a number of dimensions using properties -->
   <property name="kinect_body_x" value="0.07271" />
   <property name="kinect_body_y" value="0.27794" />
   <property name="kinect_body_z" value="0.033" />
   
   <property name="kinect_base_x" value="0.072" />
   <property name="kinect_base_y" value="0.085" />
   <property name="kinect_base_z" value="0.021" />
   
   <property name="kinect_base_post_height" value="0.016" />
   <property name="kinect_base_post_radius" value="0.005" />

   <property name="PI" value="3.1415" />
         
   <!-- Define a box-shaped camera link for the Kinect -->
   <macro name="camera" params="parent name color *origin">
      <joint name="${parent}_${name}_joint" type="fixed">
         <xacro:insert_block name="origin" />
         <parent link="${parent}"/>
         <child link="${name}_base_link"/>
      </joint>
      
      <link name="${name}_base_link">
         <visual>
            <origin xyz="0 0.0 0.0" rpy="0 0 0" />
            <geometry>
               <box size="${kinect_base_x} ${kinect_base_y} ${kinect_base_z}"/>
            </geometry>
            <material name="${color}" />
         </visual>
         <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
               <box size="${kinect_base_x} ${kinect_base_y} ${kinect_base_z}"/>
            </geometry>
         </collision>
      </link>
      
      <joint name="${name}_base_post_joint" type="fixed">
         <origin xyz="0 0 ${(kinect_base_z + kinect_base_post_height)/2}" rpy="0 0 0" />
         <parent link="${name}_base_link" />
         <child link="${name}_base_post_link" />
      </joint>
      
      <link name="${name}_base_post_link">
         <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
               <cylinder radius="${kinect_base_post_radius}" length="${kinect_base_post_height}"/>
            </geometry>
            <material name="${color}" />
         </visual>
         <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
               <cylinder radius="${kinect_base_post_radius}" length="${kinect_base_post_height}"/>
            </geometry>
         </collision>
      </link>
    
      <joint name="${name}_base_joint" type="fixed">
         <origin xyz="0 0 ${(kinect_base_post_height + kinect_body_z)/2}" rpy="0 0 0" />
         <parent link="${name}_base_post_link" />
         <child link="${name}_link" />
      </joint>
      
      <link name="${name}_link">
         <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
               <box size="${kinect_body_x} ${kinect_body_y} ${kinect_body_z}"/>
            </geometry>
            <material name="${color}" />
         </visual>
         <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
               <box size="${kinect_body_x} ${kinect_body_y} ${kinect_body_z}"/>
            </geometry>
         </collision>
      </link>
    
      <joint name="${name}_depth_joint" type="fixed">
         <origin xyz="0 0.0125 0" rpy="0 0 0" />
          <parent link="${name}_link" />
          <child link="${name}_depth_frame" />
      </joint>

      <link name="${name}_depth_frame">
      <inertial>
         <mass value="0.000001" />
         <origin xyz="0 0 0" />
         <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
            iyy="0.0001" iyz="0.0"
            izz="0.0001" />
         </inertial>
      </link>

      <joint name="${name}_depth_optical_joint" type="fixed">
         <origin xyz="0 0 0" rpy="${-PI/2} 0 ${-PI/2}" />
         <parent link="${name}_depth_frame" />
         <child link="${name}_depth_optical_frame" />
      </joint>

      <link name="${name}_depth_optical_frame">
         <inertial>
            <mass value="0.000001" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001" />
         </inertial>
      </link>

      <joint name="${name}_rgb_joint" type="fixed">
         <origin xyz="0 -0.0125 0" rpy="0 0 0" />
         <parent link="${name}_link" />
         <child link="${name}_rgb_frame" />
      </joint>

      <link name="${name}_rgb_frame">
         <inertial>
         <mass value="0.000001" />
         <origin xyz="0 0 0" />
         <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
            iyy="0.0001" iyz="0.0"
            izz="0.0001" />
         </inertial>
      </link>

      <joint name="${name}_rgb_optical_joint" type="fixed">
         <origin xyz="0 0 0" rpy="${-PI/2} 0 ${-PI/2}" />
         <parent link="${name}_rgb_frame" />
         <child link="${name}_rgb_optical_frame" />
      </joint>

      <link name="${name}_rgb_optical_frame">
         <inertial>
            <mass value="0.000001" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001" />
         </inertial>
      </link>

      <gazebo reference="${name}_link"> 
      <sensor type="depth" name="${name}">
	<always_on>true</always_on> 
	<update_rate>20.0</update_rate> 
	<!--camera> 
		<horizontal_fov>${60.0*PI/180.0}</horizontal_fov> 
		<image> 
			<format>B8G8R8</format> 
			<width>640</width> 
			<height>480</height> 
		</image>
		<clip> 
			<near>0.05</near> 
			<far>8.0</far> 
		</clip> 
	</camera-->
      <plugin name="${name}_link_controller" filename="libgazebo_ros_openni_kinect.so">

        <baseline>0.2</baseline>

        <alwaysOn>true</alwaysOn>

        <updateRate>10</updateRate>

        <cameraName>${name}_ir</cameraName>

        <imageTopicName>/${name}/rgb/image_raw</imageTopicName>

        <cameraInfoTopicName>/${name}/rgb/camera_info</cameraInfoTopicName>

        <depthImageTopicName>/${name}/depth/image_raw</depthImageTopicName>

        <depthImageInfoTopicName>/${name}/depth/camera_info</depthImageInfoTopicName>

        <pointCloudTopicName>/${name}/depth/points</pointCloudTopicName>

        <frameName>${name}_depth_optical_frame</frameName>

        <pointCloudCutoff>0.5</pointCloudCutoff>

        <distortionK1>0.00000001</distortionK1>

        <distortionK2>0.00000001</distortionK2>

        <distortionK3>0.00000001</distortionK3>

        <distortionT1>0.00000001</distortionT1>

        <distortionT2>0.00000001</distortionT2>

        <CxPrime>0</CxPrime>

        <Cx>0</Cx>

        <Cy>0</Cy>

        <focalLength>0</focalLength>

        <hackBaseline>0</hackBaseline>

      </plugin>
	 </sensor>
    </gazebo>
   </macro>
    
</robot>
