// Generated by gencpp from file my_sensor/FakeSensorRequest.msg
// DO NOT EDIT!


#ifndef MY_SENSOR_MESSAGE_FAKESENSORREQUEST_H
#define MY_SENSOR_MESSAGE_FAKESENSORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_sensor
{
template <class ContainerAllocator>
struct FakeSensorRequest_
{
  typedef FakeSensorRequest_<ContainerAllocator> Type;

  FakeSensorRequest_()
    {
    }
  FakeSensorRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::my_sensor::FakeSensorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_sensor::FakeSensorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FakeSensorRequest_

typedef ::my_sensor::FakeSensorRequest_<std::allocator<void> > FakeSensorRequest;

typedef boost::shared_ptr< ::my_sensor::FakeSensorRequest > FakeSensorRequestPtr;
typedef boost::shared_ptr< ::my_sensor::FakeSensorRequest const> FakeSensorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_sensor::FakeSensorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_sensor::FakeSensorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_sensor

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'my_sensor': ['/home/mypc/ROSex/mybot_ws/devel/share/my_sensor/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_sensor::FakeSensorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_sensor::FakeSensorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_sensor::FakeSensorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_sensor::FakeSensorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_sensor::FakeSensorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_sensor::FakeSensorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_sensor::FakeSensorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::my_sensor::FakeSensorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::my_sensor::FakeSensorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_sensor/FakeSensorRequest";
  }

  static const char* value(const ::my_sensor::FakeSensorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_sensor::FakeSensorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::my_sensor::FakeSensorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_sensor::FakeSensorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FakeSensorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_sensor::FakeSensorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::my_sensor::FakeSensorRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MY_SENSOR_MESSAGE_FAKESENSORREQUEST_H
