// Generated by gencpp from file my_sensor/Light.msg
// DO NOT EDIT!


#ifndef MY_SENSOR_MESSAGE_LIGHT_H
#define MY_SENSOR_MESSAGE_LIGHT_H

#include <ros/service_traits.h>


#include <my_sensor/LightRequest.h>
#include <my_sensor/LightResponse.h>


namespace my_sensor
{

struct Light
{

typedef LightRequest Request;
typedef LightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Light
} // namespace my_sensor


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_sensor::Light > {
  static const char* value()
  {
    return "a8e1711976dcda1b8b978eee81e85498";
  }

  static const char* value(const ::my_sensor::Light&) { return value(); }
};

template<>
struct DataType< ::my_sensor::Light > {
  static const char* value()
  {
    return "my_sensor/Light";
  }

  static const char* value(const ::my_sensor::Light&) { return value(); }
};


// service_traits::MD5Sum< ::my_sensor::LightRequest> should match 
// service_traits::MD5Sum< ::my_sensor::Light > 
template<>
struct MD5Sum< ::my_sensor::LightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_sensor::Light >::value();
  }
  static const char* value(const ::my_sensor::LightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_sensor::LightRequest> should match 
// service_traits::DataType< ::my_sensor::Light > 
template<>
struct DataType< ::my_sensor::LightRequest>
{
  static const char* value()
  {
    return DataType< ::my_sensor::Light >::value();
  }
  static const char* value(const ::my_sensor::LightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_sensor::LightResponse> should match 
// service_traits::MD5Sum< ::my_sensor::Light > 
template<>
struct MD5Sum< ::my_sensor::LightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_sensor::Light >::value();
  }
  static const char* value(const ::my_sensor::LightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_sensor::LightResponse> should match 
// service_traits::DataType< ::my_sensor::Light > 
template<>
struct DataType< ::my_sensor::LightResponse>
{
  static const char* value()
  {
    return DataType< ::my_sensor::Light >::value();
  }
  static const char* value(const ::my_sensor::LightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_SENSOR_MESSAGE_LIGHT_H
