// Auto-generated. Do not edit!

// (in-package my_sensor.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class RotationResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.fianl_orientation = null;
    }
    else {
      if (initObj.hasOwnProperty('fianl_orientation')) {
        this.fianl_orientation = initObj.fianl_orientation
      }
      else {
        this.fianl_orientation = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type RotationResult
    // Serialize message field [fianl_orientation]
    bufferOffset = _serializer.float32(obj.fianl_orientation, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type RotationResult
    let len;
    let data = new RotationResult(null);
    // Deserialize message field [fianl_orientation]
    data.fianl_orientation = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_sensor/RotationResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'dba2fa577764980591f9c40310bc94fe';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    float32 fianl_orientation
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new RotationResult(null);
    if (msg.fianl_orientation !== undefined) {
      resolved.fianl_orientation = msg.fianl_orientation;
    }
    else {
      resolved.fianl_orientation = 0.0
    }

    return resolved;
    }
};

module.exports = RotationResult;
