// Generated by gencpp from file yrobot_home_bringup/joint_msg.msg
// DO NOT EDIT!


#ifndef YROBOT_HOME_BRINGUP_MESSAGE_JOINT_MSG_H
#define YROBOT_HOME_BRINGUP_MESSAGE_JOINT_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yrobot_home_bringup
{
template <class ContainerAllocator>
struct joint_msg_
{
  typedef joint_msg_<ContainerAllocator> Type;

  joint_msg_()
    : id(0)
    , r(0.0)  {
    }
  joint_msg_(const ContainerAllocator& _alloc)
    : id(0)
    , r(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef double _r_type;
  _r_type r;





  typedef boost::shared_ptr< ::yrobot_home_bringup::joint_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yrobot_home_bringup::joint_msg_<ContainerAllocator> const> ConstPtr;

}; // struct joint_msg_

typedef ::yrobot_home_bringup::joint_msg_<std::allocator<void> > joint_msg;

typedef boost::shared_ptr< ::yrobot_home_bringup::joint_msg > joint_msgPtr;
typedef boost::shared_ptr< ::yrobot_home_bringup::joint_msg const> joint_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yrobot_home_bringup::joint_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yrobot_home_bringup::joint_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yrobot_home_bringup

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'yrobot_home_bringup': ['/home/mypc/ROSex/y-robot_ws/src/yrobot_home_bringup/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::yrobot_home_bringup::joint_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yrobot_home_bringup::joint_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yrobot_home_bringup::joint_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yrobot_home_bringup::joint_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yrobot_home_bringup::joint_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yrobot_home_bringup::joint_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yrobot_home_bringup::joint_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "348422e71c7da9fe3e7cde970aaddd6e";
  }

  static const char* value(const ::yrobot_home_bringup::joint_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x348422e71c7da9feULL;
  static const uint64_t static_value2 = 0x3e7cde970aaddd6eULL;
};

template<class ContainerAllocator>
struct DataType< ::yrobot_home_bringup::joint_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yrobot_home_bringup/joint_msg";
  }

  static const char* value(const ::yrobot_home_bringup::joint_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yrobot_home_bringup::joint_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 id\n\
float64 r\n\
";
  }

  static const char* value(const ::yrobot_home_bringup::joint_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yrobot_home_bringup::joint_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct joint_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yrobot_home_bringup::joint_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yrobot_home_bringup::joint_msg_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "r: ";
    Printer<double>::stream(s, indent + "  ", v.r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YROBOT_HOME_BRINGUP_MESSAGE_JOINT_MSG_H
