controller_list:
  - name: yrobot_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - shouder_arm_joint
      - upper_arm_joint
      - middle_arm_joint
      - fore_arm_joint
      - tool_joint
