(cl:defpackage my_sensor-msg
  (:use )
  (:export
   "<ROTATIONACTION>"
   "ROTATIONACTION"
   "<ROTATIONACTIONFEEDBACK>"
   "ROTATIONACTIONFEEDBACK"
   "<ROTATIONACTIONGOAL>"
   "ROTATIONACTIONGOAL"
   "<ROTATIONACTIONRESULT>"
   "ROTATIONACTIONRESULT"
   "<ROTATIONFEEDBACK>"
   "ROTATIONFEEDBACK"
   "<ROTATIONGOAL>"
   "ROTATIONGOAL"
   "<ROTATIONRESULT>"
   "ROTATIONRESULT"
  ))

