; Auto-generated. Do not edit!


(cl:in-package my_sensor-msg)


;//! \htmlinclude RotationResult.msg.html

(cl:defclass <RotationResult> (roslisp-msg-protocol:ros-message)
  ((fianl_orientation
    :reader fianl_orientation
    :initarg :fianl_orientation
    :type cl:float
    :initform 0.0))
)

(cl:defclass RotationResult (<RotationResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RotationResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RotationResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_sensor-msg:<RotationResult> is deprecated: use my_sensor-msg:RotationResult instead.")))

(cl:ensure-generic-function 'fianl_orientation-val :lambda-list '(m))
(cl:defmethod fianl_orientation-val ((m <RotationResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_sensor-msg:fianl_orientation-val is deprecated.  Use my_sensor-msg:fianl_orientation instead.")
  (fianl_orientation m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RotationResult>) ostream)
  "Serializes a message object of type '<RotationResult>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'fianl_orientation))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RotationResult>) istream)
  "Deserializes a message object of type '<RotationResult>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'fianl_orientation) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RotationResult>)))
  "Returns string type for a message object of type '<RotationResult>"
  "my_sensor/RotationResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RotationResult)))
  "Returns string type for a message object of type 'RotationResult"
  "my_sensor/RotationResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RotationResult>)))
  "Returns md5sum for a message object of type '<RotationResult>"
  "dba2fa577764980591f9c40310bc94fe")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RotationResult)))
  "Returns md5sum for a message object of type 'RotationResult"
  "dba2fa577764980591f9c40310bc94fe")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RotationResult>)))
  "Returns full string definition for message of type '<RotationResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 fianl_orientation~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RotationResult)))
  "Returns full string definition for message of type 'RotationResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float32 fianl_orientation~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RotationResult>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RotationResult>))
  "Converts a ROS message object to a list"
  (cl:list 'RotationResult
    (cl:cons ':fianl_orientation (fianl_orientation msg))
))
