right_front_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - right_front_shoulder_joint
    - right_front_3_joint
    - right_front_2_joint
    - right_front_1_joint
